name: CI/CD Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          echo "Automated Deployment Successful!"
          echo "Running on AWS EC2 Runner"
          ls -la